name: error404project
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to

version: 1.0.0+1

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.4
  cupertino_icons: ^1.0.2
  curved_navigation_bar: ^1.0.1
  image_picker: ^0.8.6+7
  go_router: ^14.8.1
  socket_io_client: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^4.0.0


flutter:
  assets:
    - lib/img/default-user-avt.png
    - lib/img/todo.jpg
    - lib/img/click.png

  uses-material-design: true

